#!/bin/bash
#
#skripti algus
#
echo -n "sisesta (oma) vanus:" # väljastab jutumärkides oleva teksti
read vanus # teksti aktiveerimisel saab sisestada midagi
if test $vanus -gt 0 -a $vanus -lt 11 # väljastab teate kui oled laps
then
            echo "oled laps"
elif test $vanus -ge 11 -a $vanus -lt 18 # väljastab teate kui oled nooruk
then
            echo "oled nooruk"
elif test $vanus -ge 18 -a $vanus -lt 63 # väljastab teate kui oled täiskasvanu
then
            echo "oled täiskasvanu"
elif test $vanus -ge 63 # väljastab teate kui oled senioor
then
            echo "oled senioor"
else
            echo "vigane sisend" # väljastab teate kui sisestatakse väle vanuse väärtus
fi

#skripti lõpp
