#!/bin/bash

osch=0
echo "1. Unix (Sun OS)"
echo "2. Linux (Red Hat)"

echo -n "Vali enda operatsioonisüsteem [1 or 2]? "
read osch

if [ $osch -eq 1 ] ; then
	echo "Valisid (Sun OS) operatsioonisüsteemi!"
else
	if [ $osch -eq 2 ] ; then
		echo "Valisid (Red Hat) operatsioonisüsteemi!"
	else
		echo "Kas sulle ei meeldi Unix/Linux OS?"
	fi
fi
