#!/bin/bash

echo -n "Sisesta kuu number: "
read kuu

case $kuu in
	"1") echo "See on jaanuar";;
	"2") echo "See on veebruar";;
	"3") echo "see on märts";;
	"4") echo "see on aprill";;
	"5") echo "see on mai";;
	"6") echo "see on juuni";;
	"7") echo "see on juuli";;
	"8") echo "see on august";;
	"9") echo "see on september";;
	"10") echo "see on oktoober";;
	"11") echo "see on november";;
	"12") echo "see on detsember";;
esac
