#!/bin/bash
echo
echo -n " Sisestage a kylje vaartus: " 
read a
echo -n "Sisestage b kylje vaartus: "
read b 
echo -n "Sisestage c kylje vaartus:  "
read c

p= `echo "scale=2;)$a+$b+$c)/2" | bc`
s= `echo "scale=2;sqrt($p*($p-$a)*($p-$b)*($p-$c))" | bc`

echo "Pindala = $s"
