#!/bin/bash

echo -n "Sisesta ridade arv: " #sisestab ridade arvu
	read rida #rida
		echo -n "Sisesta tärnide arv reas: " #sisestab tärnide arvu
			read tarn #tärn
for (( i = 1; i <= rida; i++ ))
	do
		echo -n "$i "
	for (( j = 1; j <= tarn; j++ ))
do
	echo -n "*"
done
	echo ""
done
